[package]
name = "prophetouw/cleanit"
version = "1.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "A memory cleaning helper."
authors = ["ProphetOuw <ouwproduction@gmail.com>"]